version: "3.9"

services:
  test:
    build: .     #them vao           
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 -m pytest

  run:
    build: .     #Them vao           
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 main.py
