version: '3.8'

services:
  app:
    build: .
    container_name: exercise_3_container
    environment:
      - AWS_ACCESS_KEY_ID=doanxem
      - AWS_SECRET_ACCESS_KEY=bimat
      - AWS_REGION=us-east-1
    volumes:
      - .:/app
    command: python main.py